---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patches:
  - target:
      kind: ClusterVersion
      name: version
    path: overlays/patch-cluster-version.yaml
